apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-k8s

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-k8s-cronjob
  namespace: hello-world-k8s
spec:
  schedule: "* * * * *" # Runs every minute
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: hello-world-k8s-app
              image: teqniqly/hello-world:k8s
              command: ["dotnet", "HelloWorld.dll"]
              resources:
                requests:
                  memory: "16Mi"
                  cpu: "100m"
                limits:
                  memory: "64Mi"
                  cpu: "200m"
          restartPolicy: Never
