apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-k8s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  namespace: hello-world-k8s
data:
  appsettings.json: |
    {
      "ApiBaseAddress": "https://api.openweathermap.org",
      "ApiKey": "<API_KEY_PLACEHOLDER>"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret
  namespace: hello-world-k8s
type: Opaque
data:
  ApiKey: <BASE64_ENCODED_API_KEY>

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-k8s-cronjob
  namespace: hello-world-k8s
spec:
  schedule: "* * * * *" # Runs every minute
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: hello-world-k8s-app
              image: teqniqly/hello-world:k8s
              imagePullPolicy: Always
              command: ["dotnet", "HelloWorld.dll"]
              env:
                - name: ApiKey
                  valueFrom:
                    secretKeyRef:
                      name: hello-world-secret
                      key: ApiKey
              volumeMounts:
                - name: config-volume
                  mountPath: /app/appsettings.json
                  subPath: appsettings.json
              resources:
                requests:
                  memory: "16Mi"
                  cpu: "100m"
                limits:
                  memory: "64Mi"
                  cpu: "200m"
          volumes:
            - name: config-volume
              configMap:
                name: hello-world-config
          restartPolicy: Never
